version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: moviecatalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/movie
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
